-- =====================================================
-- Purpose:
--   Physical Star Schema for E-Commerce Sales.
--
-- Source OLTP schema:
--   customer_app in 01_customer_app_schema_strict_postgres.sql
--
-- Design focus:
--   - One and only one fact table: fact_sales.
--   - Grain: one row per purchased product line, mapped from order_items.
--   - All analysis context is represented as dimensions directly connected
--     to fact_sales, keeping the model a star schema.
--
-- Research basis:
--   The design follows the e-commerce sales warehouse pattern from:
--   "Data Warehouse Design for E-Commerce Environments".
--   It applies the classic dimensional process:
--     1) choose the business process: e-commerce sales
--     2) choose the grain: sales transaction line
--     3) choose dimensions: time, customer, product, shop, promotion,
--        payment, shipping, and location
--     4) choose facts: quantity, gross sales, discounts, tax, shipping,
--        and net sales
--
-- Adaptation to the current database:
--   - order_items is the atomic sales line source.
--   - orders contributes order-level totals, status, customer, addresses.
--   - products/product_variants/categories/shops become product/shop context.
--   - payments and shipments are dimensions/status context only here.
--   - vouchers are represented by dim_promotion as a promotion combination,
--     because the OLTP schema allows many vouchers on one order.
-- =====================================================


DROP SCHEMA IF EXISTS dwh CASCADE;
CREATE SCHEMA dwh;
SET search_path TO dwh, public;


-- =====================================================
-- 1. TIME DIMENSIONS
-- =====================================================

CREATE TABLE dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE UNIQUE,
    day_of_week SMALLINT,
    day_name VARCHAR(10),
    day_of_month SMALLINT,
    day_of_year SMALLINT,
    week_of_year SMALLINT,
    month_number SMALLINT,
    month_name VARCHAR(10),
    quarter_number SMALLINT,
    year_number SMALLINT,
    is_weekend BOOLEAN,
    is_month_end BOOLEAN,
    season_name VARCHAR(12),
    fiscal_year SMALLINT,
    fiscal_quarter SMALLINT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dim_time (
    time_key INTEGER PRIMARY KEY,
    full_time TIME UNIQUE,
    hour_24 SMALLINT,
    minute_number SMALLINT,
    second_number SMALLINT,
    am_pm VARCHAR(2),
    day_part VARCHAR(20),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =====================================================
-- 2. SALES ANALYSIS DIMENSIONS
-- =====================================================

CREATE TABLE dim_customer (
    customer_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_customer_id INTEGER UNIQUE,
    public_customer_id UUID,

    username VARCHAR(50),
    email VARCHAR(120),
    first_name VARCHAR(80),
    last_name VARCHAR(80),
    full_name VARCHAR(170),
    phone_number VARCHAR(30),
    customer_status VARCHAR(30),
    registered_at TIMESTAMP,
    last_login_at TIMESTAMP,

    effective_from TIMESTAMP NOT NULL DEFAULT TIMESTAMP '1900-01-01',
    effective_to TIMESTAMP NOT NULL DEFAULT TIMESTAMP '9999-12-31',
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dim_location (
    location_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_address_id INTEGER,
    source_customer_id INTEGER,
    natural_location_hash TEXT UNIQUE,

    address_type VARCHAR(30),
    recipient_name VARCHAR(120),
    phone_number VARCHAR(30),
    street VARCHAR(255),
    ward VARCHAR(100),
    district VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(30),
    country VARCHAR(100),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dim_shop (
    shop_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_shop_id INTEGER UNIQUE,
    public_shop_id UUID,

    shop_name VARCHAR(160),
    shop_slug VARCHAR(160),
    shop_status VARCHAR(30),
    shop_created_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dim_category (
    category_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_category_id INTEGER UNIQUE,
    source_parent_category_id INTEGER,

    category_name VARCHAR(140),
    category_slug VARCHAR(140),
    parent_category_name VARCHAR(140),
    is_active BOOLEAN,
    category_created_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dim_product (
    product_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_product_id INTEGER,
    source_product_variant_id INTEGER UNIQUE,
    public_product_id UUID,
    public_variant_id UUID,

    product_sku VARCHAR(100),
    product_slug VARCHAR(220),
    product_name VARCHAR(220),
    brand VARCHAR(120),
    product_status VARCHAR(30),
    is_featured BOOLEAN,

    variant_sku VARCHAR(120),
    variant_name VARCHAR(220),
    variant_status VARCHAR(30),
    variant_options_json JSONB,
    is_default_variant BOOLEAN,
    current_unit_price NUMERIC(12,2),
    compare_at_price NUMERIC(12,2),
    currency CHAR(3),
    stock_quantity INTEGER,
    reserved_quantity INTEGER,
    weight_kg NUMERIC(8,3),

    product_attributes_json JSONB,
    product_images_json JSONB,
    variant_images_json JSONB,
    product_created_at TIMESTAMP,
    variant_created_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(source_product_id, source_product_variant_id)
);

CREATE TABLE dim_promotion (
    promotion_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    natural_promotion_hash TEXT UNIQUE,

    promotion_type VARCHAR(30) NOT NULL DEFAULT 'none',
    voucher_count INTEGER NOT NULL DEFAULT 0 CHECK (voucher_count >= 0),
    voucher_codes TEXT,
    voucher_names TEXT,
    discount_types TEXT,
    promotion_scope VARCHAR(30),
    promotion_start_at TIMESTAMP,
    promotion_end_at TIMESTAMP,
    minimum_order_amount NUMERIC(12,2),
    is_active BOOLEAN,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dim_payment (
    payment_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    natural_payment_hash TEXT UNIQUE,

    payment_method VARCHAR(50),
    payment_method_group VARCHAR(50),
    payment_status VARCHAR(30),
    paid_flag BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dim_shipping (
    shipping_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    natural_shipping_hash TEXT UNIQUE,

    carrier VARCHAR(100),
    shipment_status VARCHAR(30),
    shipped_flag BOOLEAN NOT NULL DEFAULT FALSE,
    delivered_flag BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =====================================================
-- 3. UNKNOWN / NOT APPLICABLE DIMENSION MEMBERS
-- =====================================================

INSERT INTO dim_date (
    date_key, full_date, day_of_week, day_name, day_of_month, day_of_year,
    week_of_year, month_number, month_name, quarter_number, year_number,
    is_weekend, is_month_end, season_name, fiscal_year, fiscal_quarter
)
VALUES (
    0, NULL, NULL, 'Unknown', NULL, NULL,
    NULL, NULL, 'Unknown', NULL, NULL,
    NULL, NULL, 'Unknown', NULL, NULL
);

INSERT INTO dim_time (
    time_key, full_time, hour_24, minute_number, second_number, am_pm, day_part
)
VALUES (0, NULL, NULL, NULL, NULL, 'NA', 'Unknown');

INSERT INTO dim_customer (
    customer_key, source_customer_id, username, full_name, customer_status
)
OVERRIDING SYSTEM VALUE
VALUES (0, NULL, 'unknown', 'Unknown Customer', 'unknown');

INSERT INTO dim_location (
    location_key, natural_location_hash, address_type, city, country
)
OVERRIDING SYSTEM VALUE
VALUES (0, 'unknown', 'unknown', 'Unknown', 'Unknown');

INSERT INTO dim_shop (
    shop_key, source_shop_id, shop_name, shop_status
)
OVERRIDING SYSTEM VALUE
VALUES (0, NULL, 'Unknown Shop', 'unknown');

INSERT INTO dim_category (
    category_key, source_category_id, category_name, category_slug, is_active
)
OVERRIDING SYSTEM VALUE
VALUES (0, NULL, 'Unknown Category', 'unknown', FALSE);

INSERT INTO dim_product (
    product_key, source_product_id, source_product_variant_id,
    product_sku, product_name, variant_sku, variant_name,
    product_status, variant_status
)
OVERRIDING SYSTEM VALUE
VALUES (
    0, NULL, NULL,
    'unknown', 'Unknown Product', 'unknown', 'Unknown Variant',
    'unknown', 'unknown'
);

INSERT INTO dim_promotion (
    promotion_key, natural_promotion_hash, promotion_type, voucher_count,
    voucher_codes, promotion_scope, is_active
)
OVERRIDING SYSTEM VALUE
VALUES (0, 'none', 'none', 0, 'NO_VOUCHER', 'none', FALSE);

INSERT INTO dim_payment (
    payment_key, natural_payment_hash, payment_method, payment_method_group,
    payment_status, paid_flag
)
OVERRIDING SYSTEM VALUE
VALUES (0, 'unknown', 'unknown', 'unknown', 'unknown', FALSE);

INSERT INTO dim_shipping (
    shipping_key, natural_shipping_hash, carrier, shipment_status,
    shipped_flag, delivered_flag
)
OVERRIDING SYSTEM VALUE
VALUES (0, 'unknown', 'unknown', 'unknown', FALSE, FALSE);


-- =====================================================
-- 4. FACT TABLE: E-COMMERCE SALES
-- =====================================================
-- Grain:
--   One row per source order_items row.
--
-- Additive facts:
--   quantity, gross_sales_amount, discount_amount, tax_amount,
--   shipping_amount_allocated, net_sales_amount.
--
-- Degenerate dimensions:
--   order_number, source_order_id, source_order_item_id, statuses.
-- =====================================================

CREATE TABLE fact_sales (
    sales_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_date_key INTEGER NOT NULL REFERENCES dim_date(date_key),
    order_time_key INTEGER NOT NULL REFERENCES dim_time(time_key),
    customer_key BIGINT NOT NULL REFERENCES dim_customer(customer_key),
    product_key BIGINT NOT NULL REFERENCES dim_product(product_key),
    shop_key BIGINT NOT NULL REFERENCES dim_shop(shop_key),
    category_key BIGINT NOT NULL REFERENCES dim_category(category_key),
    promotion_key BIGINT NOT NULL REFERENCES dim_promotion(promotion_key),
    payment_key BIGINT NOT NULL REFERENCES dim_payment(payment_key),
    shipping_key BIGINT NOT NULL REFERENCES dim_shipping(shipping_key),
    ship_to_location_key BIGINT NOT NULL REFERENCES dim_location(location_key),
    bill_to_location_key BIGINT NOT NULL REFERENCES dim_location(location_key),

    source_order_id INTEGER NOT NULL,
    source_order_item_id INTEGER NOT NULL,
    order_number VARCHAR(60) NOT NULL,
    order_status VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,

    source_customer_id INTEGER,
    source_product_id INTEGER,
    source_product_variant_id INTEGER,
    source_shop_id INTEGER,
    source_category_id INTEGER,

    currency CHAR(3) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_amount NUMERIC(12,2) NOT NULL CHECK (unit_price_amount >= 0),
    gross_sales_amount NUMERIC(12,2) NOT NULL CHECK (gross_sales_amount >= 0),
    line_discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (line_discount_amount >= 0),
    order_discount_amount_allocated NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (order_discount_amount_allocated >= 0),
    total_discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_discount_amount >= 0),
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    shipping_amount_allocated NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (shipping_amount_allocated >= 0),
    net_sales_amount NUMERIC(12,2) NOT NULL CHECK (net_sales_amount >= 0),

    order_created_at TIMESTAMP NOT NULL,
    order_item_created_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(source_order_id, source_order_item_id)
);


-- =====================================================
-- 5. PHYSICAL INDEXING FOR STAR-SCHEMA QUERY PATTERNS
-- =====================================================

CREATE INDEX idx_dim_customer_source ON dim_customer(source_customer_id);
CREATE INDEX idx_dim_customer_status ON dim_customer(customer_status);
CREATE INDEX idx_dim_location_city_country ON dim_location(city, country);
CREATE INDEX idx_dim_shop_source ON dim_shop(source_shop_id);
CREATE INDEX idx_dim_shop_status ON dim_shop(shop_status);
CREATE INDEX idx_dim_category_parent ON dim_category(source_parent_category_id);
CREATE INDEX idx_dim_product_source_product ON dim_product(source_product_id);
CREATE INDEX idx_dim_product_source_variant ON dim_product(source_product_variant_id);
CREATE INDEX idx_dim_product_brand ON dim_product(brand);
CREATE INDEX idx_dim_product_status ON dim_product(product_status, variant_status);
CREATE INDEX idx_dim_promotion_type ON dim_promotion(promotion_type);
CREATE INDEX idx_dim_payment_method_status ON dim_payment(payment_method, payment_status);
CREATE INDEX idx_dim_shipping_carrier_status ON dim_shipping(carrier, shipment_status);

CREATE INDEX idx_fact_sales_order_date ON fact_sales(order_date_key);
CREATE INDEX idx_fact_sales_customer ON fact_sales(customer_key);
CREATE INDEX idx_fact_sales_product ON fact_sales(product_key);
CREATE INDEX idx_fact_sales_shop ON fact_sales(shop_key);
CREATE INDEX idx_fact_sales_category ON fact_sales(category_key);
CREATE INDEX idx_fact_sales_promotion ON fact_sales(promotion_key);
CREATE INDEX idx_fact_sales_payment ON fact_sales(payment_key);
CREATE INDEX idx_fact_sales_shipping ON fact_sales(shipping_key);
CREATE INDEX idx_fact_sales_ship_to_location ON fact_sales(ship_to_location_key);
CREATE INDEX idx_fact_sales_bill_to_location ON fact_sales(bill_to_location_key);
CREATE INDEX idx_fact_sales_source_order ON fact_sales(source_order_id);
CREATE INDEX idx_fact_sales_status ON fact_sales(order_status, payment_status);

-- =====================================================
-- End of Physical Star Schema for E-Commerce Sales
-- =====================================================
