environment: local

postgres:
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  database: ${POSTGRES_DB:ecommerce}
  user: ${POSTGRES_USER:admin}
  password: ${POSTGRES_PASSWORD:admin}

lakehouse:
  base_path: ./data/lake
  format: parquet

batch:
  watermark_path: ./data/state/watermarks.json

spark:
  app_name: ecommerce-batch-local
  master: local[*]
  config:
    spark.sql.shuffle.partitions: "4"
    spark.jars.packages: org.postgresql:postgresql:42.7.3
